# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hsianch/test_MSPM/test_MSPM.srcs/sources_1/ip/fifo_wrapper_infill/fifo_wrapper_infill.xci
# IP: The module: 'fifo_wrapper_infill' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hsianch/test_MSPM/test_MSPM.gen/sources_1/ip/fifo_wrapper_infill/fifo_wrapper_infill.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrapper_infill'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hsianch/test_MSPM/test_MSPM.gen/sources_1/ip/fifo_wrapper_infill/fifo_wrapper_infill_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrapper_infill'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hsianch/test_MSPM/test_MSPM.srcs/sources_1/ip/fifo_wrapper_infill/fifo_wrapper_infill.xci
# IP: The module: 'fifo_wrapper_infill' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hsianch/test_MSPM/test_MSPM.gen/sources_1/ip/fifo_wrapper_infill/fifo_wrapper_infill.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrapper_infill'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hsianch/test_MSPM/test_MSPM.gen/sources_1/ip/fifo_wrapper_infill/fifo_wrapper_infill_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wrapper_infill'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
